# Generated by Django 2.1.2 on 2019-03-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='year_release',
            new_name='datetime_release',
        ),
    ]
