# Generated by Django 2.1.2 on 2019-03-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190327_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='datetime_release',
            field=models.DateField(blank=True, null=True),
        ),
    ]
