# Generated by Django 2.1.2 on 2019-03-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20190327_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.ManyToManyField(to='movie.Type'),
        ),
    ]
