# Generated by Django 2.1.2 on 2019-03-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20190327_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.ManyToManyField(blank=True, null=True, to='movie.Type'),
        ),
    ]
