# Generated by Django 2.1.2 on 2019-04-05 07:35

from django.db import migrations, models
import movie.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20190327_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_images',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=movie.models.movie_image_path, validators=[movie.models.validate_image]),
        ),
    ]
