"""
Django settings for MovieStore project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '6^)988*g61lri^@v+ix@1c9r2%^80wn5r)5=nw41ybo2o8!3l6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['0.0.0.0', '127.0.0.1']


# set login redirect
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = '/'
# set sub url
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'order',
    'user',
    'movie',
    'cart',
]

MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MovieStore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'templatetags': 'templatetags.templatetags',

            }
        },
    },
]

WSGI_APPLICATION = 'MovieStore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # },

    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'isddb',
    #     'USER': 'postgres',
    #     'PASSWORD': '10102001',
    #     'HOST': 'localhost',
    #     'PORT': '5432',
    # },

    # - DBSERVER = ds121332.mlab.com:21332
    #                                - DBUSER = joelnguyen1010
    #                                           - DBPASSWORD = Hoilamcho1010
    #                                                          - DBNAME = devbooking
    #                                                                     - DBPORT = 4222

    'default': {
        'ENGINE': os.environ.get('DBENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.environ.get('DBNAME', 'db.sqlite3'),
        'USER': os.environ.get('DBUSER', 'user'),
        'PASSWORD': os.environ.get('DBPASSWORD', 'password'),
        'HOST': os.environ.get('DBHOST', 'localhost'),
        'PORT': os.environ.get('DBPORT', '5432'),
    },

}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'

# <<<<<<< HEAD
# =======
# STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'static')
# >>>>>>> e075e077477f4d1019c5ed2d48e0df16709df9af

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/images')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')


    # STATIC_ROOT,
    # '/home/urban/shareibc-backend-django/static/'
]

STATIC_ROOT = ''
