# Generated by Django 2.1.2 on 2019-05-17 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_movie_price'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='movies',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='movie.Movie'),
        ),
    ]
