# Generated by Django 2.1.2 on 2019-05-25 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20190525_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='movies',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='movie.Movie'),
        ),
    ]
