# Generated by Django 2.1.2 on 2019-05-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_movie_price'),
        ('order', '0004_auto_20190525_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='movies',
        ),
        migrations.AddField(
            model_name='order',
            name='movies',
            field=models.ManyToManyField(null=True, to='movie.Movie'),
        ),
    ]
