# Generated by Django 2.1.2 on 2019-05-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190525_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='movies',
            field=models.ManyToManyField(to='movie.Movie'),
        ),
    ]
