# Generated by Django 2.1.2 on 2019-05-25 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20190525_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieorder',
            name='movies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.Movie'),
        ),
    ]
