# Generated by Django 2.1.2 on 2019-05-25 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20190525_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
    ]
