# Generated by Django 2.1.2 on 2019-05-26 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20190525_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Shipment'),
        ),
    ]
