# Generated by Django 2.1.2 on 2019-05-30 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20190526_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 30, 11, 13, 19, 41565)),
        ),
    ]
